name: Lint and Validate dbt SQL

on:
  # Can be manually triggered
  workflow_dispatch: {}
  pull_request: {}

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dbt and SQLFluff
        run: |
          pip install dbt-snowflake sqlfluff sqlfluff-templater-dbt

      - name: Run SQLFluff lint
        run: |
          sqlfluff lint --dialect snowflake orchestration/dagster_pipeline/assets/dbt/main/models

      - name: Test dbt compilation (requires Snowflake connection)
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DB: ${{ secrets.SNOWFLAKE_DB }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        run: |
          cd orchestration/dagster_pipeline/assets/dbt/main
          dbt compile