name: Lint SQL Python and Javascript

on:
  # Can be manually triggered
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install packages required for Python and SQL linting
        run: |
          pip install dbt-snowflake sqlfluff sqlfluff-templater-dbt black

      - name: Install and run XO linting for Javascript
        working-directory: presentation/streaming_dashboard
        run: |
          npm install xo
          npx xo "**/*.js" --ignore-pattern="**/node_modules/**" --no-eslintrc

      - name: Cache dbt packages
        uses: actions/cache@v3
        with:
          path: orchestration/dagster_pipeline/assets/dbt/main/dbt_packages
          key: ${{ runner.os }}-dbt-deps-${{ hashFiles('orchestration/dagster_pipeline/assets/dbt/main/packages.yml') }}
          restore-keys: |
            ${{ runner.os }}-dbt-deps-

      - name: Run SQLFluff lint
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DB: ${{ secrets.SNOWFLAKE_DB }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        run: |
          cd orchestration/dagster_pipeline/assets/dbt/main
          dbt deps
          sqlfluff lint models/ || {
            echo "::error::SQL formatting issues found. Run sqlfluff fix locally."
            exit 1
          }

      - name: Auto-fix Python with Black
        run: black .

      - name: Commit Python fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "Github Actions Linting (Black)"
            file_pattern: "*.py"
